### ISSUE TITLE
Function to return a BCP 47 language tag

### ISSUE THREAD

**Issue by binarykitchen** [petert82/country-query#3]
For some complex date handling I am looking for a function which returns me a BCP 47 language tag based on a TLD alone.

The locales parameter in this infamous function

```js
dateObj.toLocaleTimeString([locales[, options]])
```

(see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString)

can be a string with a BCP 47 language tag. Unfortunately you do not return a BCP 47 language tag in your results.

Could that be added in your array? And for performance, introduce a flag so that only this one is returned without anything else.

Thanks!

**Comment by binarykitchen** [comment]
@petert82 hello?

**Comment by petert82** [comment]
Hi,
I think this would be best accomplished via a change to the [source dataset](https://github.com/mledoze/countries). You'd probably be best directing a request to add the extra data needed there.

If that's not possible, and you're really concerned about performance, you might be better served by just pre-compiling your own mapping of TLDs to BCP 47 lang tags (you could I think construct these from the data in the mledoze/countries data plus a mapping of 3-letter language codes to 2-letter codes).
