### ISSUE TITLE
[BUG] Venezuela currency is wrong

### ISSUE THREAD

**Issue by tuang3142** [petert82/country-query#9]
Currently, the currency for Venezuela is VES but country-query returns VEF.
```javascript
CountryQuery.find('cca2', 've')
=> ["VEF"]
```
It is because we are using the old `world-country` package (2.1.1). It should be updated to the latest version.

**Comment by petert82** [comment]
Thanks for flagging this. I've just published [version 2.0.0](https://github.com/petert82/country-query/releases/tag/2.0.0) which includes the most recent version of the `world-countries` package, so should fix this.
